---
language: node_js
node_js:
  - "lts/*"

install:
  - npm install

script:
  - tsc winsim.ts

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
