---
language: node_js
node_js:
  - "lts/*"

install:
  - npm install

script:
  - tsc --target es5 winsim.ts

deploy:
  provider: script
  skip-cleanup: true
  script: ./deploy.sh
  on:
    branch: master
